# Generated by Django 5.2.4 on 2025-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=50)),
                ('accused', models.CharField(max_length=100)),
                ('victim', models.CharField(max_length=100)),
                ('allegations', models.TextField()),
                ('facts_summary', models.TextField()),
                ('date_of_incident', models.DateField()),
                ('representatives', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
