# Generated by Django 5.2.4 on 2025-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
